services:
  morooi-telegram-bot-go:
    container_name: morooi-telegram-bot-go
    image: morooi/morooi-telegram-bot-go:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/user/telegram.db:/app/telegram.db
    environment:
      TOKEN: "YOUR TELEGRAM BOT API TOKEN"
      KEY: "YOUR ENCRYPTION KEY"
      XRAY_API_HOST: "127.0.0.1"
      XRAY_API_PORT: "8080"
      XRAY_STATS_ADMIN: "XXXXXXX"
      XRAY_STATS_CRON: "*/5 * * * *"
      SERVER_TRAFFIC_CRON: "0 */6 * * *"
      BWG_VEID: "XXXXXXX"
      BWG_API_KEY: "XXXXXXX"
      SEND_MESSAGE_CHANNEL_ID: "XXXXXXX"
    restart: unless-stopped